### ISSUE TITLE
Create a critique of your website by answering the following questions: 

### ISSUE THREAD

**Issue by brandong954** [jrpeden/cs373-idb#131]
```
What did we do well?
What did we learn?
What can we do better?
What puzzles us?
```

**Comment by tiras-j** [comment]
Some input:
What did we learn?
That it's better to utilize a beefier database from the get-go such as PostgreSQL over MySQL so that you avoid headaches of data migration (and infrastructure migration, i.e. all the build scripts and requirements lists) later on. Our particular issue was with SQLAlchemy only have full text search support for PostgreSQL, and the third party implementations for other databases didn't support Python3. Overall choosing a beefier database also has the benefit of the wealth of support that's been built around that database. 

What can we do better?
Currently we are letting flask serve HTTP requests directly, this is not particularly scalable. If flask were to go down the entire site would crash. Rather we should hide flask as an application server behind a reverse HTTP proxy such as Apache or NGINX which will actually spawn multiple instances of the flask application server and dynamically route requests between them. This way if any of the flask instances crashes, our HTTP reverse proxy and simply route to another application server and possibly even restart the crashed server. This would increase the reliability of the site dramatically as well as scaling better for higher requests rates as the requests are routed to separate application servers.

**Comment by jrpeden** [comment]
Done.
