### ISSUE TITLE
Implement the RESTful API

### ISSUE THREAD

**Issue by jrpeden** [jrpeden/cs373-idb#66]
Take what we described on Apiary and actually implement it.
Update Apiary if the API actually differs from the plan.

**Comment by brandong954** [comment]
Hey Josh, we'll work in tandem on this one. I've implemented the front-end to make calls to your API on the back-end. Since my implementation is technically not working until you finish the API, I suggest we work together on another feature branch for the time being. I'm going to call it "api_imp." ("imp" is short for implementation). This way we won't break the dev branch. 

I noticed you have multiple API calls for different attributes. I suggest we consolidate the calls for each model into two routes. One route (e.g. /resource/teams) will grab all the data for teams and dump it into a json object to send back to the front-end, and another route (e.g. /resource/teams/<id>) will dump all the data for a specific team into a json object. I can then parse the json objects on the front-end for the specific properties I'm looking for. 

What do you think though?

**Comment by brandong954** [comment]
DONE!
